# Generated by Django 3.0.5 on 2021-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, help_text='Напишите название жанра', max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
