# Generated by Django 3.0.5 on 2021-03-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, help_text='Напишите название категории', max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
