# Generated by Django 3.0.5 on 2021-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='yamdbuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='yamdbuser',
            name='code',
            field=models.TextField(blank=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail'),
        ),
    ]
