# Generated by Django 3.0.5 on 2021-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210323_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='created',
            field=models.DateField(blank=True, default='2021-01-01', verbose_name='Дата создания'),
        ),
    ]
