# Generated by Django 3.0.5 on 2021-03-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_yamdbuser_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='password',
        ),
    ]
