# Generated by Django 3.0.5 on 2021-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_yamdbuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='password',
            field=models.CharField(default='admin', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
