# Generated by Django 3.0.5 on 2021-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_yamdbuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.TextField(blank=True, verbose_name='Имя пользователя'),
        ),
    ]
