# Generated by Django 3.0.5 on 2021-03-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210325_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yamdbuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='yamdbuser',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
    ]
