# Generated by Django 3.0.5 on 2021-03-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210326_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yamdbuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='yamdbuser',
            name='unique_username',
        ),
    ]
